config/routes.rb
TrainingDeals::Application.routes.draw do
  
  resources :users, except: [:index, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :training_methods do
    collection { post :sort }
  end
  resources :durations do
    collection { post :sort }
  end
  resources :content_lengths do
    collection { post :sort }
  end
  resources :genres do
    collection { post :sort }
    resources :categories, shallow: true 
  end
  resources :categories do
    resources :topics, shallow: true
  end
  resources :exchange_rates, only: [:index, :create]
  resources :my_businesses do
    resources :ownerships, except: :show, shallow: true do
      collection { post :sort }
    end
    resources :products, shallow: true do
      get 'newprod', on: :new              #'new' route - html only
    end
    resources :events, shallow: true
    resources :previous_events, only: [:index], shallow: true
  end
  resources :genre_selections, only: [:new, :create] do
    resources :category_selections, only: [:new, :create]
  end
  resources :category_selections, only: [:new, :create] do
    resources :topic_selections, only: [:new, :create]
  end
  resources :topic_selections, only: [:new, :create]
  resources :results do
    collection do
      get 'filter_by_method'
    end
  end
  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
    resources :businesses, only: [:index, :show, :destroy]
  end

  root  'static_pages#home'
  match '/signup',                    to: 'users#new',                              via: 'get'
  match '/signin',                    to: 'sessions#new',                           via: 'get'
  match '/signout',                   to: 'sessions#destroy',                       via: 'delete'
  match '/about',                     to: 'static_pages#about',                     via: 'get'
  match '/contact',                   to: 'static_pages#contact',                   via: 'get'
  match '/admin_menu',                to: 'static_pages#admin_menu',                via: 'get'
  match '/select_categories',         to: 'static_pages#select_categories',         via: 'get'
  match '/select_topics',             to: 'static_pages#select_topics',             via: 'get'
  match '/genre_totals',              to: 'static_pages#genre_totals',              via: 'get'
  match '/category_totals',           to: 'static_pages#category_totals',           via: 'get'
  match '/topic_totals',              to: 'static_pages#topic_totals',              via: 'get'
  match '/filter_by_method',          to: 'results#filter_by_method',               via: 'get' 
  match '/filter_by_qualification',   to: 'results#filter_by_qualification',        via: 'get'
  match '/filter_by_supplier',        to: 'results#filter_by_supplier',             via: 'get'
  match '/filter_by_keyword',         to: 'results#filter_by_keyword',              via: 'get'
  match '/filter_by_location',        to: 'results#filter_by_location',             via: 'get'
  match '/filter_by_price',           to: 'results#filter_by_price',                via: 'get'
  match '/sort_by_arrangement',       to: 'results#sort_by_arrangement',            via: 'get'
  match '/framework',                 to: 'admin_pages#framework',                  via: 'get'
  match '/users_menu',                to: 'admin_pages#users_menu',                 via: 'get'
  match '/vendors_menu',              to: 'admin_pages#vendors_menu',               via: 'get'
  match '/feedback',                  to: 'admin_pages#feedback',                   via: 'get'
  match '/billings',                  to: 'admin_pages#billings',                   via: 'get'
  match '/text_editor',               to: 'admin_pages#text_editor',                via: 'get'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  	before_action :home_open, only: :home
  	before_action :not_admin, only: :admin_menu

  	def home
      @genres = Genre.with_topics.order("description")
      @categories = Category.with_topics.where("categories.genre_id =?", Genre.first)
      @topics = Topic.where("status =? and category_id=?", 1, @categories.first)	
  	end

  	def about
  	end

  	def contact
  	end

  	def admin_menu
  	end

    def select_categories
      @genre = Genre.find(params[:genre_id])
      @genre_count = @genre.active_products.count
      @categories = Category.with_topics
        .where("categories.genre_id = ? and categories.status = ?", params[:genre_id], 1) 
      @topics = Topic.where("status =? and category_id=?", 1, @categories.first)
      respond_to do |format|
        format.js
      end
    end

    def select_topics
      @category = Category.find(params[:category_id])
      @category_count = @category.active_products.count
      @topics = Topic.where("category_id = ? and status = ?", params[:category_id], 1)
          .order("description")
      respond_to do |format|
        format.js
      end
    end

    def genre_totals
      @genre = Genre.find(params[:genre_id])
      @genre_count = @genre.active_products.count
      respond_to do |format|
        format.js
      end
    end

    def category_totals
      @category = Category.find(params[:category_id])
      @category_count = @category.active_products.count
      respond_to do |format|
        format.js
      end
    end

    def topic_totals
      @topic = Topic.find(params[:topic_id])
      @topic_count = @topic.active_products.count
      respond_to do |format|
        format.js
      end
    end


  	private
  		def home_open
  			if signed_in?
          if current_user.admin?
    				redirect_to admin_menu_path
          else
            redirect_to current_user
          end
    		end
    	end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_total_category.html.erb
(<%= number_with_delimiter(@category_count) %> found)

app/views/static_pages/_total_genre.html.erb
(<%= number_with_delimiter(@genre_count) %> found)

app/views/static_pages/_total_topic.html.erb
(<%= number_with_delimiter(@topic_count) %> found)

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
	<em>HROOMPH::Training</em> aims to be web's most comprehensive and reliable index of training and self-development programmes - no matter where or how you want to study.  But it's not just a neutral database.  When you train, we want to help you to gain!
</p>
<h3>If you're selling training ...</h3>
<p>
	Whether you offer courses, seminars, books, or online materials, it's <em>FREE</em> to list all your standard products and services.
</p>
<p>
	<b>Optimize your sales.</b> Fill those last places in your class or run a special promotion.
</p>
<h3>If you're looking for training ...</h3>
<p>
	Search for the course you want, the training format, the maximum cost, maybe a location, date and qualification.
</p>
<p>
	<b>Optimize your budget.</b> Sign up for free and we'll give you early notice of any special deals matching your preferences.
</p>

app/views/static_pages/admin_menu.html.erb
<% provide(:title, "Admin menu") %>
<span class="two-line-header"><h1>Admin menu</h1></span>
<h2>( HROOMPH Admins only )</h2>

<div class="row">
	<aside class="span3">
		<section>
			<%= render "/shared/admin_menu_side" %>
		</section>
	</aside>
	<div class="span8">
		<ul id="menus">
			<li><%= link_to "Framework", framework_path %></li>
			<li><%= link_to "Users", admin_users_path %></li>
			<li><%= link_to "Vendors", admin_businesses_path %></li>
			<li><%= link_to "Feedback", "#" %></li>
			<li><%= link_to "Site activity", "#" %></li>
			<li><%= link_to "Billing", "#" %></li>
			<li><%= link_to "Text editor", "#" %></li>
		</ul>
	</div>
</div>

app/views/static_pages/category_totals.js.erb
$(".display-total").html('<%= escape_javascript(render :partial => "total_category") %>');

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>Contact us at admin@hroomph.com.</p>
	

app/views/static_pages/genre_totals.js.erb
$(".display-total").html('<%= escape_javascript(render :partial => "total_genre") %>');

app/views/static_pages/home.html.erb
<div class="row">
	<aside class="span3">
		<section>
			<div class="add-bottom-space">
				<%= number_with_delimiter(pluralize(Product.live.count, "topic")) %> to choose from.<br />
				What's yours?
			</div>

			<%= form_tag results_path, method: 'get', 
							id: "products_search" do %>

		
				<%= select "genre", "genre_id",
					@genres.pluck(:description, :id), 
				 	{ prompt: true },
					{ id: 'genre_select' } %>
  
  				<div class="hidden-content">
	  				
	  				<%= select "category", "category_id",
	  					@categories.pluck(:description, :id),
	  					{ include_blank: "Select a category" }, 
	  					{ id: 'cat_select' } %>
	  			</div>

	  			<div class="hidden-content-2">
				
					<%= select "topic", "topic_id", 
						@topics.pluck(:description, :id), 
						{ include_blank: "Select a topic" },
						{ id: "topic_select" } %>

				</div>
			
				<%= submit_tag "View results", name: nil, class: "btn btn-primary btn-small" %> 
				<div class="display-total"></div>
			<% end %>
		</section>
		<section>
			<div class="explain">
				<p>From the Results page, you can further refine your search, by:-</p>
				<ul>
					<li>Learning style <em>(training course, book, seminar, mentoring etc)</em></li>
					<li>Maximum price</li>
					<li>Supplier</li>
					<li>Qualification</li>
					<li>Distance from you</li>
					<li>Customer ratings</li>
					<li>A key word or phrase</li>
				</ul>
			</div>
		</section>
	</aside>
	<div class="span8">
		<div class="center hero-unit">
			<h1><%= image_tag("hroomph_title.png", alt: "HROOMPH - The Training app") %></h1>

			<h2>
				Optimizing training budgets.  Maximizing training sales.
			</h2>

			<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
		</div>
	</div>
</div>

app/views/static_pages/topic_totals.js.erb
$(".display-total").html('<%= escape_javascript(render :partial => "total_topic") %>');