config/routes.rb
TrainingDeals::Application.routes.draw do
  
  resources :users, except: [:index, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :training_methods do
    collection { post :sort }
  end
  resources :durations do
    collection { post :sort }
  end
  resources :content_lengths do
    collection { post :sort }
  end
  resources :genres do
    collection { post :sort }
    resources :categories, shallow: true 
  end
  resources :categories do
    resources :topics, shallow: true
  end
  resources :exchange_rates, only: [:index, :create]
  resources :my_businesses do
    resources :ownerships, except: :show, shallow: true do
      collection { post :sort }
    end
    resources :products, shallow: true do
      get 'newprod', on: :new              #'new' route - html only
    end
    resources :events, shallow: true
    resources :previous_events, only: [:index], shallow: true
  end
  resources :genre_selections, only: [:new, :create] do
    resources :category_selections, only: [:new, :create]
  end
  resources :category_selections, only: [:new, :create] do
    resources :topic_selections, only: [:new, :create]
  end
  resources :topic_selections, only: [:new, :create]
  resources :results do
    collection do
      get 'filter_by_method'
    end
  end
  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
    resources :businesses, only: [:index, :show, :destroy]
  end

  root  'static_pages#home'
  match '/signup',                    to: 'users#new',                              via: 'get'
  match '/signin',                    to: 'sessions#new',                           via: 'get'
  match '/signout',                   to: 'sessions#destroy',                       via: 'delete'
  match '/about',                     to: 'static_pages#about',                     via: 'get'
  match '/contact',                   to: 'static_pages#contact',                   via: 'get'
  match '/admin_menu',                to: 'static_pages#admin_menu',                via: 'get'
  match '/select_categories',         to: 'static_pages#select_categories',         via: 'get'
  match '/select_topics',             to: 'static_pages#select_topics',             via: 'get'
  match '/genre_totals',              to: 'static_pages#genre_totals',              via: 'get'
  match '/category_totals',           to: 'static_pages#category_totals',           via: 'get'
  match '/topic_totals',              to: 'static_pages#topic_totals',              via: 'get'
  match '/filter_by_method',          to: 'results#filter_by_method',               via: 'get' 
  match '/filter_by_qualification',   to: 'results#filter_by_qualification',        via: 'get'
  match '/filter_by_supplier',        to: 'results#filter_by_supplier',             via: 'get'
  match '/filter_by_keyword',         to: 'results#filter_by_keyword',              via: 'get'
  match '/filter_by_location',        to: 'results#filter_by_location',             via: 'get'
  match '/filter_by_price',           to: 'results#filter_by_price',                via: 'get'
  match '/sort_by_arrangement',       to: 'results#sort_by_arrangement',            via: 'get'
  match '/framework',                 to: 'admin_pages#framework',                  via: 'get'
  match '/users_menu',                to: 'admin_pages#users_menu',                 via: 'get'
  match '/vendors_menu',              to: 'admin_pages#vendors_menu',               via: 'get'
  match '/feedback',                  to: 'admin_pages#feedback',                   via: 'get'
  match '/billings',                  to: 'admin_pages#billings',                   via: 'get'
  match '/text_editor',               to: 'admin_pages#text_editor',                via: 'get'

end

app/views/shared/_admin_menu_links.html.erb
<li><%= link_to "Admin home page", admin_menu_path %></li>
<li><%= link_to "Framework", framework_path %></li>
<li><%= link_to "Users", admin_users_path %></li>
<li><%= link_to "Vendors", admin_businesses_path %></li>
<li><%= link_to "Feedback", "#" %></li>
<li><%= link_to "Site activity", "#" %></li>
<li><%= link_to "Billing", "#" %></li>
<li><%= link_to "Text editor", "#" %></li>
<li class="divider"></li>
<li><%= link_to "User home page", user_path(current_user) %></li>
<% if current_user.has_businesses? %>
	<li class="divider"></li>
	<li><%= link_to "Business home page", my_businesses_path %></li>
<% else %>
	<li><%= link_to "Add a business", my_businesses_path %></li>
<% end %>

app/views/shared/_business_active_products.html.erb
<% unless @business.current_training_methods.length == 0 %>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th></th>
			<th class="numeric">No of products</th>
			<th class="numeric">Current items / events</th>
			<th class="numeric">Previous</th>
		</tr>
		<% @business.current_training_methods.each do |method| %>
			<tr>
				<td><%= method.description %></td>
				<td class="numeric"><%= @business.count_products(true, method.id) %></td>
				<td class="numeric">
					<% if method.event? %>
						<%= @business.count_scheduled_events_for_products(true, method.id) %>
					<% else %>
						<%= @business.count_products(true, method.id) %>
					<% end %>
				</td>
				<td class="numeric">
					<% if method.event? %>
						<%= @business.count_previous_events_for_products(true, method.id) %>
					<% else %>
						0
					<% end %>
				</td>
			</tr>
		<% end %>
	</table>

<% else %>
	<div class="no-content">-- None --</div>
<% end %>

app/views/shared/_business_contact_details.html.erb
<div><%= @business.street_address %></div>
<div><%= @business.email %></div>
<% unless @business.all_phones_vendor == "Not shown" %>
	<div><%= @business.all_phones_vendor %></div>
<% end %>
<% if @business.website? %>
	<div>Website: <%= link_to(@business.website, "#{@business.website}", target: "_blank") %></div>
<% end %>
<div>Added by <%= @founder.name %> <em>&lt;<%= @founder.email %>&gt;</em> 
	on <%= formatted_shortdate(@business.created_at) %>
</div>

app/views/shared/_business_delisted_products.html.erb
<% unless @business.old_training_methods.length == 0 %>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th></th>
			<th class="numeric">No of products</th>
			<th class="numeric">Items / events</th>
		</tr>
		<% @business.old_training_methods.each do |oldmethod| %>
			<tr>
				<td><%= oldmethod.description %></td>
				<td class="numeric"><%= @business.count_products(false, oldmethod.id) %></td>
				<td class="numeric"> 
					<% if oldmethod.event? %>
						<%= @business.count_previous_events_for_products(false, 
								oldmethod.id) %>
					<% else %>
						<%= @business.count_products(false, oldmethod.id) %>
					<% end %>
				</td>
			</tr>
		<% end %>
	</table>
<% else %>
	<div class="no-content">-- None --</div>
<% end %>

app/views/shared/_business_details.html.erb
<div class="paragraph">
	<div class="subject">About us:</div>
	<div class="detail"><%= @business.description %></div>
</div>
<div class="paragraph">
	<% unless @business.hide_address? %>
		<div>
			<div class="subject"><em>Address:</em></div>
			<div class="detail"> <%= @business.street_address %></div>
		</div>
	<% end %>
	<% if @business.has_contactable_users? %>
	  	<div class="clearer">
			<div class="subject">Contact:</div>
			<div class="detail"><%= @business.contactable_owners_list %></div>
	  	</div>
	<% else %>
		<% unless @business.phone.blank? && @business.alt_phone.blank? %>
			<div class="clearer">
				<div class="subject">Phone:</div>
				<div class="detail"><%= @business.all_phones_vendor %></div>
			</div>
		<% end %>
		<div class="clearer">
			<div class="subject">Email:</div>
			<div class="detail"><%= @business.email %></div>
		</div>
	<% end %>
</div>
<% if @business.website? %>
	<div class="paragraph">
		<div class="subject">Website:</div>
		<div class="detail">
			<%= link_to(@business.website, "#{@business.website}", target: "_blank") %>
		</div>
	</div>
<% end %>
<% if @business.image? %>
	<div class="paragraph">
		<div class="subject">Image:</div>
		<div class="detail">
			<%= image_tag @business.image_url, class: "img-rounded" %>
		</div>
	</div>
<% end %>

app/views/shared/_business_menu.html.erb
<div class="well sidebar-nav">
	<ul class="nav nav-list">
		<div id="menu-items" class = "js-menu">
			<li class="dropdown">
				<a class="dropdown-toggle" data-toggle="dropdown" href="#"> 
					<span class="toggler-menu column-wide">
						<span class="label label-info">MENU 
							<span id="ct-menu" class="caret down"></span>
						</span>
					</span>
				</a>
				<ul class="dropdown-menu" role="menu">
					<% if current_user.has_businesses? && !@business.nil? %>
						<%= render '/shared/business_menu_links' %>
					<% else %>
						<%= render '/shared/business_menu_minimized_links' %>
					<% end %>
				</ul>
			</li>
		</div>

		<div class="html-menu">
			<span class="column-wide"><li class="label label-info">MENU</li></span>
			<li class="divider"></li>
			<% if current_user.has_businesses? && !@business.nil? %>
				<%= render '/shared/business_menu_links' %>
			<% else %>
				<%= render '/shared/business_menu_minimized_links' %>
			<% end %>
		</div>
	</ul>
</div>

app/views/shared/_business_menu_minimized_links.html.erb
<li><%= link_to "User home page", user_path(current_user) %></li>
<% if current_user.admin? %>
	<li class="divider"></li>
	<li><%= link_to "Admin home page", admin_menu_path %></li>
<% end %>

app/views/shared/_business_menu_new.html.erb
<div class="well sidebar-nav">
	<ul class="nav nav-list">
		<div class = "js-menu">
			<li class="dropdown">
				<a class="dropdown-toggle" data-toggle="dropdown" href="#"> 
					<span class="toggler-menu column-wide">
						<span class="label label-info">MENU 
							<span id="ct-menu" class="caret down"></span>
						</span>
					</span>
				</a>
				<ul class="dropdown-menu" role="menu">
					<%= render '/shared/business_menu_new_links' %>
				</ul>
			</li>
		</div>

		<div class="html-menu">
			<span class="column-wide"><li class="label label-info">MENU</li></span>
			<li class="divider"></li>
			<%= render '/shared/business_menu_new_links' %>
		</div>
	</ul>
</div>

app/views/shared/_business_menu_new_links.html.erb
<li><%= link_to "Business home page", my_businesses_path %></li>
<li class="divider"></li>
<li><%= link_to "User home page", user_path(current_user) %></li>
<% if current_user.admin? %>
	<li class="divider"></li>
	<li><%= link_to "Admin home page", admin_menu_path %></li>
<% end %>

app/views/shared/_business_team.html.erb
<ul>
	<% @ownerships.each do |ownership| %>
		<li>
			<% if ownership.contactable? %>
				<span class="contact glyphicon glyphicon-headphones"></span>&nbsp;&nbsp;
			<% end %>
			<%= ownership.user.name %> <i> <%= "<#{ownership.user.email}>" %></i>
			<% if ownership.contactable %>
				<% unless ownership.phone.blank? %>
					<span class="mobile glyphicon glyphicon-phone"></span>
					<%= ownership.phone %>
				<% end %>
			<% end %>
		</li>
	<% end %>
</ul>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_product_details.html.erb
<div class="paragraph">
	<div>
		<div class="subject">Classification:</div>
		<div class="detail"><%= @product.topic.classification %></div>
	</div>
	<% if @product.ref_code? %>
		<div class="clearer">
			<div class="subject">Reference code:</div>
			<div class="detail"><%= @product.ref_code_formatted %></div>
		</div>
	<% end %>
	<% if @product.qualification? %>
		<div class="clearer">
			<div class="subject">Qualification:</div>
			<div class="detail" id="qualification"><%= @product.qualification %></div>
		</div>
	<% end %>
</div>
<div class="paragraph">
	<div class="subject">Description:</div>
	<div class="detail"><%= @product.content %></div>
</div>
<div class="paragraph">
	<div class="subject">Benefits/results:</div>
	<div class="detail"><%= @product.outcome %></div>
</div>

<% if @product.web_link? %>
	<div class="paragraph">
		<div class="subject">Web-link:</div>
		<div class="detail">
			<%= link_to(@product.web_link, "#{@product.web_link}", target: "_blank") %>
		</div>
	</div>
<% end %>
<% if @product.image? %>
	<div class="paragraph">
		<div class="subject"></div>
		<div class="detail">
			<%= image_tag @product.image_url, class: "img-rounded" %>
		</div>
	</div>
<% end %>

app/views/shared/_user_menu.html.erb
<div class="well sidebar-nav">
	<ul class="nav nav-list">
		<div class="html-menu">
			<span class="column-wide">
				<span class="label label-info">MENU
			<li class="divider"></li>
			<%= render '/shared/user_menu_links' %>

		</div>
		<div id="menu-items" class="js-menu">
			<li class="dropdown">
				<a class="dropdown-toggle" data-toggle="dropdown" href="#"> 
					<span class="toggler-menu column-wide">
						<span class="label label-info">MENU
							<span id="ct-menu" class="caret down"></span>
						</span>
					</span>
				</a>
				<ul class="dropdown-menu" role="menu">
					<%= render '/shared/user_menu_links' %>
				</ul>
			</li>
		</div>
	</ul>
</div>

app/views/shared/_user_menu_links.html.erb
<li><%= link_to "Instant search", "#" %></li>
<li><%= link_to "Saved search set-up", "#" %></li>
<li><%= link_to "Saved search results", "#" %></li>

<li><%= link_to "Training history", "#" %></li>
<li><%= link_to "Your reviews", "#" %></li>
<li><%= link_to "Favourites", "#" %></li>
<li><%= link_to "Find trainers", "#" %></li>
<li class="divider"></li>
<% if @user.has_businesses? %>
	<li><%= link_to "Business home page", my_businesses_path %></li>
<% else %>
	<li><%= link_to "Add a business", my_businesses_path %></li>
<% end %>
<% if @user.admin? %>
	<li class="divider"></li>
	<li><%= link_to "Admin home page", admin_menu_path %></li>
<% end %>