config/routes.rb
TrainingDeals::Application.routes.draw do
  
  resources :users, except: [:index, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :training_methods do
    collection { post :sort }
  end
  resources :durations do
    collection { post :sort }
  end
  resources :content_lengths do
    collection { post :sort }
  end
  resources :genres do
    collection { post :sort }
    resources :categories, shallow: true 
  end
  resources :categories do
    resources :topics, shallow: true
  end
  resources :exchange_rates, only: [:index, :create]
  resources :my_businesses do
    resources :ownerships, except: :show, shallow: true do
      collection { post :sort }
    end
    resources :products, shallow: true do
      get 'newprod', on: :new              #'new' route - html only
    end
    resources :events, shallow: true
    resources :previous_events, only: [:index], shallow: true
  end
  resources :genre_selections, only: [:new, :create] do
    resources :category_selections, only: [:new, :create]
  end
  resources :category_selections, only: [:new, :create] do
    resources :topic_selections, only: [:new, :create]
  end
  resources :topic_selections, only: [:new, :create]
  resources :results do
    collection do
      get 'filter_by_method'
    end
  end
  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
    resources :businesses, only: [:index, :show, :destroy]
  end

  root  'static_pages#home'
  match '/signup',                    to: 'users#new',                              via: 'get'
  match '/signin',                    to: 'sessions#new',                           via: 'get'
  match '/signout',                   to: 'sessions#destroy',                       via: 'delete'
  match '/about',                     to: 'static_pages#about',                     via: 'get'
  match '/contact',                   to: 'static_pages#contact',                   via: 'get'
  match '/admin_menu',                to: 'static_pages#admin_menu',                via: 'get'
  match '/select_categories',         to: 'static_pages#select_categories',         via: 'get'
  match '/select_topics',             to: 'static_pages#select_topics',             via: 'get'
  match '/genre_totals',              to: 'static_pages#genre_totals',              via: 'get'
  match '/category_totals',           to: 'static_pages#category_totals',           via: 'get'
  match '/topic_totals',              to: 'static_pages#topic_totals',              via: 'get'
  match '/filter_by_method',          to: 'results#filter_by_method',               via: 'get' 
  match '/filter_by_qualification',   to: 'results#filter_by_qualification',        via: 'get'
  match '/filter_by_supplier',        to: 'results#filter_by_supplier',             via: 'get'
  match '/filter_by_keyword',         to: 'results#filter_by_keyword',              via: 'get'
  match '/filter_by_location',        to: 'results#filter_by_location',             via: 'get'
  match '/filter_by_price',           to: 'results#filter_by_price',                via: 'get'
  match '/sort_by_arrangement',       to: 'results#sort_by_arrangement',            via: 'get'
  match '/framework',                 to: 'admin_pages#framework',                  via: 'get'
  match '/users_menu',                to: 'admin_pages#users_menu',                 via: 'get'
  match '/vendors_menu',              to: 'admin_pages#vendors_menu',               via: 'get'
  match '/feedback',                  to: 'admin_pages#feedback',                   via: 'get'
  match '/billings',                  to: 'admin_pages#billings',                   via: 'get'
  match '/text_editor',               to: 'admin_pages#text_editor',                via: 'get'

end

app/controllers/admin_pages_controller.rb
class AdminPagesController < ApplicationController

    before_action :not_admin
    
    def framework
        @time_ref = ExchangeRate.last_updated
    end

    def users_menu
    end

    def vendors_menu
    end

    def feedback
    end

    def billings
    end

    def text_editor
    end

end

app/helpers/admin_pages_helper.rb
module AdminPagesHelper
end

app/views/admin_pages/billings.html.erb
<h1>AdminPages#billings</h1>
<p>Find me in app/views/admin_pages/billings.html.erb</p>

app/views/admin_pages/feedback.html.erb
<h1>AdminPages#feedback</h1>
<p>Find me in app/views/admin_pages/feedback.html.erb</p>

app/views/admin_pages/framework.html.erb
<% provide(:title, "Framework menu") %>
<h1>Framework menu</h1>

<div class="row">
	<aside class="span3">
		<section>
			<%= render "/shared/admin_menu_side" %>
		</section>
	</aside>
	<div class="span8">
		<ul id="menus">
			<li><%= link_to "Training methods", training_methods_path %></li>
			<li><%= link_to "Time periods", durations_path %></li>
			<li><%= link_to "Content lengths", content_lengths_path %></li>
			<li><%= link_to "Genres / categories / topics", genres_path %></li>
			<li><%= link_to "Currency rates", exchange_rates_path %> 
				<i><small>(last updated <%= @time_ref %>)</small></i>
			</li>

		</ul>
		<div class="navigator">
		    <%= link_to "<- Return to main admin menu", root_path %> 
		</div>
	</div>
</div>

app/views/admin_pages/text_editor.html.erb
<h1>AdminPages#text_editor</h1>
<p>Find me in app/views/admin_pages/text_editor.html.erb</p>

app/views/admin_pages/users_menu.html.erb
<h1>AdminPages#users_menu</h1>
<p>Find me in app/views/admin_pages/users_menu.html.erb</p>

app/views/admin_pages/vendors_menu.html.erb
<h1>AdminPages#vendors_menu</h1>
<p>Find me in app/views/admin_pages/vendors_menu.html.erb</p>