config/routes.rb
TrainingDeals::Application.routes.draw do
  
  resources :users, except: [:index, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :training_methods do
    collection { post :sort }
  end
  resources :durations do
    collection { post :sort }
  end
  resources :content_lengths do
    collection { post :sort }
  end
  resources :genres do
    collection { post :sort }
    resources :categories, shallow: true 
  end
  resources :categories do
    resources :topics, shallow: true
  end
  resources :exchange_rates, only: [:index, :create]
  resources :my_businesses do
    resources :ownerships, except: :show, shallow: true do
      collection { post :sort }
    end
    resources :products, shallow: true do
      get 'newprod', on: :new              #'new' route - html only
    end
    resources :events, shallow: true
    resources :previous_events, only: [:index], shallow: true
  end
  resources :genre_selections, only: [:new, :create] do
    resources :category_selections, only: [:new, :create]
  end
  resources :category_selections, only: [:new, :create] do
    resources :topic_selections, only: [:new, :create]
  end
  resources :topic_selections, only: [:new, :create]
  resources :results do
    collection do
      get 'filter_by_method'
    end
  end
  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
    resources :businesses, only: [:index, :show, :destroy]
  end

  root  'static_pages#home'
  match '/signup',                    to: 'users#new',                              via: 'get'
  match '/signin',                    to: 'sessions#new',                           via: 'get'
  match '/signout',                   to: 'sessions#destroy',                       via: 'delete'
  match '/about',                     to: 'static_pages#about',                     via: 'get'
  match '/contact',                   to: 'static_pages#contact',                   via: 'get'
  match '/admin_menu',                to: 'static_pages#admin_menu',                via: 'get'
  match '/select_categories',         to: 'static_pages#select_categories',         via: 'get'
  match '/select_topics',             to: 'static_pages#select_topics',             via: 'get'
  match '/genre_totals',              to: 'static_pages#genre_totals',              via: 'get'
  match '/category_totals',           to: 'static_pages#category_totals',           via: 'get'
  match '/topic_totals',              to: 'static_pages#topic_totals',              via: 'get'
  match '/filter_by_method',          to: 'results#filter_by_method',               via: 'get' 
  match '/filter_by_qualification',   to: 'results#filter_by_qualification',        via: 'get'
  match '/filter_by_supplier',        to: 'results#filter_by_supplier',             via: 'get'
  match '/filter_by_keyword',         to: 'results#filter_by_keyword',              via: 'get'
  match '/filter_by_location',        to: 'results#filter_by_location',             via: 'get'
  match '/filter_by_price',           to: 'results#filter_by_price',                via: 'get'
  match '/sort_by_arrangement',       to: 'results#sort_by_arrangement',            via: 'get'
  match '/framework',                 to: 'admin_pages#framework',                  via: 'get'
  match '/users_menu',                to: 'admin_pages#users_menu',                 via: 'get'
  match '/vendors_menu',              to: 'admin_pages#vendors_menu',               via: 'get'
  match '/feedback',                  to: 'admin_pages#feedback',                   via: 'get'
  match '/billings',                  to: 'admin_pages#billings',                   via: 'get'
  match '/text_editor',               to: 'admin_pages#text_editor',                via: 'get'

end

app/models/content_length.rb
class ContentLength < ActiveRecord::Base

	acts_as_list

	has_many :products			#no deletion if associated products
	
	validates :description, 		presence: true, length: { maximum: 25 },
									uniqueness: { case_sensitive: false }
end

app/controllers/content_lengths_controller.rb
class ContentLengthsController < ApplicationController
  
  before_action :not_admin

  def index
  	@lengths = ContentLength.order('position')
  end

  def new
    @length = ContentLength.new
  end

  def create
    @length = ContentLength.new(content_length_params)
    if @length.save
      flash[:success] = "'#{@length.description}' added"
      redirect_to content_lengths_path
    else
      render 'new'
    end
  end

  def edit
    @length = ContentLength.find(params[:id])
  end

  def update
    @length = ContentLength.find(params[:id])
    if @length.update_attributes(content_length_params)
      flash[:success] = "Updated to '#{@length.description}'"
      redirect_to content_lengths_path
    else
      render 'edit'
    end
  end

  def destroy
    @length = ContentLength.find(params[:id]).destroy
    flash[:success] = "'#{@length.description}' deleted"
    redirect_to content_lengths_path
  end

  def sort
    params[:content_length].each_with_index do |id, index|
      content_length = ContentLength.find(id)
      content_length.update_attribute(:position, index) if content_length
    end
    render nothing: true
  end

  private

		def content_length_params
			params.require(:content_length).permit(:description)
		end
end

app/helpers/content_lengths_helper.rb
module ContentLengthsHelper
end

app/views/content_lengths/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %> 
<div class="entry-page">
	<div class="entry">
		<div class="add-this">
			<span class="label"><%= f.label :description %></span>
		</div>
		<div class="box-fill">
			<%= f.text_field :description %>
		</div>
	</div>
	<div class="entry"></div>
</div>

app/views/content_lengths/edit.html.erb
<% provide(:title, 'Edit content length') %>
<h1>Edit content length</h1>

<div class="row">
	<aside class="span3">
		<section>
			<%= render "/shared/admin_menu_side" %>
		</section>
	</aside>
	<div class="span8">
		<%= form_for(@length) do |f| %>

		 	<%= render 'fields', f: f %>

			<%= f.submit "Confirm", class: "btn btn-primary" %>
			<div class="navigator">
				<%= link_to "<- Cancel", content_lengths_path %>
			</div>
		<% end %>
	</div>
</div> 

app/views/content_lengths/index.html.erb
<% provide(:title, 'Content lengths') %>
<h1>Content lengths</h1>
 
<div class="row">
	<aside class="span3">
		<section>
			<%= render "/shared/admin_menu_side" %>
		</section>
	</aside>

	<div class="span8">
		<ul id="lengths" class="lists" data-update-url="<%= sort_content_lengths_url %>">
			<% @lengths.each do |lng| %>
				<%= content_tag_for :li, lng do %>
					<span class="glyphicon glyphicon-sort"></span>&nbsp;&nbsp;
					<%= lng.description %>
					| <%= link_to "edit", edit_content_length_path(lng) %>
					| <%= link_to "delete", lng, method: :delete,
							data: { confirm: "Are you sure?" } %>
				<% end %>
			<% end %>
		</ul>
	</div>
	<div class="navigator">
	    <%= link_to "<- Framework menu", framework_path %> 
		| <%= link_to "Add a content length ->", new_content_length_path %>
	</div>
</div>

app/views/content_lengths/new.html.erb
<% provide(:title, 'New content length') %>
<h1>New content length</h1>

<div class="row">
	<aside class="span3">
		<section>
			<%= render "/shared/admin_menu_side" %>
		</section>
	</aside>
	<div class="span8">
		<%= form_for(@length) do |f| %>

		 	<%= render 'fields', f: f %>

			<%= f.submit "Create", class: "btn btn-primary" %>
			<div class="navigator">
				<%= link_to "<- All content lengths", content_lengths_path %>
			</div>
		<% end %>
	</div>	
</div> 